schema = 1
nixpkgs_revision = "9fbb54b33e91ee4ca368e35a78e0613c720600b3"

[[archive]]
name = "zig"
version = "0.16.0"
filename = "zig-x86_64-linux-0.16.0.tar.xz"
url = "https://ziglang.org/download/0.16.0/zig-x86_64-linux-0.16.0.tar.xz"
sha256 = "70e49664a74374b48b51e6f3fdfbf437f6395d42509050588bd49abe52ba3d00"
role = "build-tool"

[[archive]]
name = "wayland"
version = "1.26.0"
filename = "wayland-1.26.0.tar.xz"
url = "https://gitlab.freedesktop.org/wayland/wayland/-/releases/1.26.0/downloads/wayland-1.26.0.tar.xz"
sha256 = "64176eaa46e4969903e286f8e5ef8331affc17fdf03ac9b58381d2b23162b7a3"
role = "private-runtime"

[[archive]]
name = "wayland-protocols"
version = "1.49"
filename = "wayland-protocols-1.49.tar.xz"
url = "https://gitlab.freedesktop.org/wayland/wayland-protocols/-/releases/1.49/downloads/wayland-protocols-1.49.tar.xz"
sha256 = "ec4c8f74942d6dff7ace8b4ce4764f0ef9ff618a935d974ea77edee2ad240b14"
role = "build-input"

[[archive]]
name = "libdrm"
version = "2.4.134"
filename = "libdrm-2.4.134.tar.xz"
url = "https://dri.freedesktop.org/libdrm/libdrm-2.4.134.tar.xz"
sha256 = "ac5e74d157830eb8bee44c6a6bf3ad49774ef0dd2a72bdad74a8f20308b52a95"
role = "private-runtime"

[[archive]]
name = "pixman"
version = "0.46.4"
filename = "pixman-0.46.4.tar.gz"
url = "https://cairographics.org/releases/pixman-0.46.4.tar.gz"
sha256 = "d09c44ebc3bd5bee7021c79f922fe8fb2fb57f7320f55e97ff9914d2346a591c"
role = "private-runtime"

[[archive]]
name = "libxkbcommon"
version = "1.13.2"
filename = "libxkbcommon-xkbcommon-1.13.2.tar.gz"
url = "https://github.com/xkbcommon/libxkbcommon/archive/refs/tags/xkbcommon-1.13.2.tar.gz"
sha256 = "acc4d5f7c3cbba5f9f8d08d8bdbeede84ecede46792f47929aa9321873385528"
role = "private-runtime"

[[archive]]
name = "libdisplay-info"
version = "0.4.0"
filename = "libdisplay-info-0.4.0.tar.gz"
url = "https://gitlab.freedesktop.org/emersion/libdisplay-info/-/archive/0.4.0/libdisplay-info-0.4.0.tar.gz"
sha256 = "787b58aec473830b0030251ba2b880560b4b3853dc5d6961a6e9701abae29b55"
role = "private-runtime"

[[archive]]
name = "wlroots"
version = "0.20.2"
filename = "wlroots-0.20.2.tar.gz"
url = "https://gitlab.freedesktop.org/wlroots/wlroots/-/archive/0.20.2/wlroots-0.20.2.tar.gz"
sha256 = "972c7ac44b17828f4702bfae7cd8347346a3fb5b2c1076cfa2c3fcedac5ec343"
role = "private-runtime"

[[archive]]
name = "river"
version = "0.4.8"
filename = "river-0.4.8.tar.gz"
url = "https://codeberg.org/river/river/releases/download/v0.4.8/river-0.4.8.tar.gz"
sha256 = "6d4030526e307e40de357167b4d6daacb583aed353dd93e32e1314c2d34400fa"
role = "compositor"

[[zig_dependency]]
name = "pixman"
url = "https://codeberg.org/ifreund/zig-pixman/archive/v0.3.0.tar.gz"
content_hash = "pixman-0.3.0-LClMnz2VAAAs7QSCGwLimV5VUYx0JFnX5xWU6HwtMuDX"

[[zig_dependency]]
name = "wayland"
url = "https://codeberg.org/ifreund/zig-wayland/archive/v0.6.0.tar.gz"
content_hash = "wayland-0.6.0-lQa1kqz8AQADQmdNJsNhLoNHcnEGEUjrOaPV-dtEnEmX"

[[zig_dependency]]
name = "wlroots"
url = "https://codeberg.org/ifreund/zig-wlroots/archive/v0.20.1.tar.gz"
content_hash = "wlroots-0.20.1-jmOlcqNVBAB3uB5oqBTzpRlwu-FmMyyZMVAWCe5kmcSt"

[[zig_dependency]]
name = "xkbcommon"
url = "https://codeberg.org/ifreund/zig-xkbcommon/archive/v0.4.0.tar.gz"
content_hash = "xkbcommon-0.4.0-VDqIe0i2AgDRsok2GpMFYJ8SVhQS10_PI2M_CnHXsJJZ"

[[zig_dependency]]
name = "translate-c"
url = "git+https://codeberg.org/ziglang/translate-c/#57c559cf581b1fcad90494eda219f98abeb155ce"
content_hash = "translate_c-0.0.0-Q_BUWlX1BgCD1wo6uo97prlp9VJ4gxAjwN_vZ7nsSjGN"
